# Generated by Django 3.1.4 on 2022-12-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('supervisor', models.CharField(max_length=200)),
            ],
        ),
    ]
